// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myWebApp.Shared.Models
{
    [Table("UserSettings")]
    public partial class UserSettings
    {

        [Required]
        [StringLength(50)]
        public string UserName { get; set; } = "myWebApp";
        [Required]
        [StringLength(50)]
        public string PageName { get; set; } = "MovimentiCC";

        [StringLength(50)]
        public string? Setting1 { get; set; }

        [StringLength(50)]
        public string? Setting2 { get; set; }

        [StringLength(50)]
        public string? Setting3 { get; set; }

        [StringLength(50)]
        public string? Setting4 { get; set; }

        [StringLength(50)]
        public string? Setting5 { get; set; }

        [StringLength(50)]
        public string? Setting6 { get; set; }

        [StringLength(50)]
        public string? Setting7 { get; set; }

        [StringLength(50)]
        public string? Setting8 { get; set; }

        [StringLength(50)]
        public string? Setting9 { get; set; }

    }



}