// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myWebApp.Shared.Models
{
    [Table("Condizioni Pagamento")]
    public partial class CondizionePagamento
    {
        [Key]
        [StringLength(50)]
        public string Codice { get; set; }

        [Required]
        [StringLength(50)]
        public string Descrizione { get; set; }


        [StringLength(1)]
        public string Tipo { get; set; }            //R=Rimessa Diretta   B=Pagamento Bancario


        public int GGScad1 { get; set; }
        public int GGScad2 { get; set; }
        public int GGScad3 { get; set; }
        public int GGScad4 { get; set; }
        public int GGScad5 { get; set; }
        public int GGScad6 { get; set; }



        [Column("Fine Mese")]
        [StringLength(1)]
        public string FineMese { get; set; }            //S=Si  N=No


        [Column("IVA Prima Scadenza")]
        [StringLength(1)]
        public string IvaPrimaScadenza { get; set; }    //S=Si  N=No    

        [StringLength(1)]
        public string ECommerce { get; set; }           //S=Si  N=No

        public Decimal Sconto { get; set; }

        [StringLength(50)]
        public string? Gateway { get; set; }

    }



}