// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myWebApp.Shared.Models
{
    [Table("Default Fatturazione")]
    public partial class DefaultFatturazione
    {
        [Key]
        public int ID { get; set; }


        [Required]
        [Column("Ragione Sociale")]
        [StringLength(50)]
        public string RagioneSociale { get; set; }


        [StringLength(50)]
        public string Indirizzo { get; set; }


        [Column("CAP")]
        [StringLength(6)]
        public string Cap { get; set; }


        [StringLength(50)]
        public string Localita { get; set; }


        [StringLength(4)]
        public string Provincia { get; set; }


        [Column("Partita IVA")]
        [StringLength(11)]
        public string PartitaIva { get; set; }

        [StringLength(16)]
        public string CodiceFiscale { get; set; }


        [Column("Aliquota IVA")]
        public decimal AliquotaIVA { get; set; }

        [Column("Aliquota RA Agenzia")]
        public decimal AliquotaRAAgenzia { get; set; }

        [Column("Aliquota RA Consulenza")]
        public decimal AliquotaRAConsulenza { get; set; }

        [Column("Aliquota Enasarco")]
        public decimal AliquotaEnasarco { get; set; }

        [Column("Enasarco Anno")]
        public decimal EnasarcoAnno { get; set; }

        [Column("Progressivo Invio SDI")]
        public int ProgressivoInvio { get; set; }

        [StringLength(256)]
        public string UrlImgLogo { get; set; }



    }



}