// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myWebApp.Shared.Models
{
    [Table("Dettaglio Fatture")]
    public partial class DettaglioFattura
    {

        [Required]
        public int Anno { get; set; }

        [Required]
        [StringLength(10)]
        [Column("Numero Fattura")]
        public string NumeroFattura { get; set; }

        [Required]
        [Column("Numero Riga")]
        public int NumeroRiga { get; set; }

        [Required]
        [StringLength(1)]
        [Column("Tipo Riga")]
        public string TipoRiga { get; set; }


        [StringLength(60)]
        public string? Descrizione { get; set; }



        [StringLength(100)]
        public string? Aggiuntiva { get; set; }




        public decimal Quantita { get; set; }



        public decimal Prezzo { get; set; }


        [Column("Valore Riga")]
        public decimal ValoreRiga { get; set; }


        [Column("Aliquota IVA")]
        public decimal AliquotaIVA { get; set; }




    }





}