// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myWebApp.Shared.Models
{
    [Table("Testate Fatture")]
    public partial class TestataFattura
    {

        [Required]
        public int Anno { get; set; }

        [Required]
        [StringLength(10)]
        [Column("Numero Fattura")]
        public string NumeroFattura { get; set; }

        [Required]
        [StringLength(1)]
        [Column("Tipo Fattura")]
        public string TipoFattura { get; set; } = "N";     //E=Agenzia, C=Consulenza, N=Normale, A=Accompagnatoria, F=Forfait



        [Required]
        [StringLength(20)]
        [Column("Codice Cliente")]
        public string CodiceCliente { get; set; }

        [NotMapped]
        public string RagioneSociale { get; set; }

        [Required]
        [Column("Anno Competenza Enasarco")]
        public int AnnoCompetenzaEnasarco { get; set; } = DateTime.Today.Year;

        [Required]
        [Column("Data Fattura")]
        public DateTime DataFattura { get; set; } = DateTime.Today;


        [Required]
        [StringLength(10)]
        public string Pagamento { get; set; }

        [Column("Totale Imponibile")]
        public decimal TotaleImponibile { get; set; } = 0;


        [Column("Totale Non Imponibile")]
        public decimal TotaleNonImponibile { get; set; } = 0;


        [Column("Totale Imposta")]
        public decimal TotaleImposta { get; set; } = 0;


        [Column("Totale RA")]
        public decimal TotaleRA { get; set; } = 0;


        [Column("Totale ENASARCO")]
        public decimal TotaleENASARCO { get; set; } = 0;


        public decimal ScontoPagamento { get; set; }


        [Column("Totale Fattura")]
        public decimal TotaleFattura { get; set; } = 0;


        [StringLength(1)]
        public string Saldo { get; set; } = "N";


        [Column("Importo Pagato")]
        public decimal ImportoPagato { get; set; } = 0;


        [Column("Data Pagamento")]
        public DateTime? DataPagamento { get; set; }

        [StringLength(1)]
        public string InviataSDI { get; set; } = "N";



        [Column("Codice Indirizzo")]
        [StringLength(10)]
        public string CodiceIndirizzo { get; set; }


        [StringLength(50)]
        public string Username { get; set; }

        [NotMapped]
        public bool GeneraMovimentoSaldo { get; set; } = false;

    }

    public class StatisticaFatturato
    {
        //Questa classe è utilizzata per restituire un insieme di dati statistici
        //ad esempio Mesi e relativo fatturato, oppure Cliente e Relativo Fatturato
        public string xValue { get; set; }
        public decimal yValue { get; set; }
    }



}