// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace myWebApp.Shared.Models
{
    [Table("Causali C/C")]
    public partial class CausaleCC
    {
        [Key]
        [StringLength(36)]
        public string IDCausale { get; set; } = Guid.NewGuid().ToString();


        [Required]
        [StringLength(50)]
        [Column("Descrizione Causale")]
        public string Descrizione { get; set; } = String.Empty;


        [Required]
        [StringLength(1)]
        [Column("Tipo Causale")]
        public string Tipo { get; set; } = "U";      //E=Entrata  U=Uscita

    }



}


